server:
  port: 10301

spring:
  application:
    name: business-server
  #业务配置
  datasource:
    username: root
    password: Walsn2333
    url: jdbc:mysql://localhost:3306/elm?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

#业务配置
logging:
  level:
    org.springframework: debug
    com.neusoft.mapper: debug
#业务配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.po

#eureka配置
eureka:
  client:
    service-url:
      #将自己注册给defaultZone所指定的eureka server集群上
      defaultZone: http://eurekaServer13000:13000/eureka/,http://eurekaServer13001:13001/eureka/
  instance:
    prefer-ip-address: true   #使用ip地址向eureka server进行注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #设置eureka控制台中显示的注册信息
    lease-renewal-interval-in-seconds: 5         #续约间隔时间
    lease-expiration-duration-in-seconds: 15     #续约到期时间

feign:
  hystrix:
    enabled: true     #在feign中开启hystrix熔断机制